version: '3.1'
services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: bash -c "printenv && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file: ./.env
    tty: true
    stdin_open: true
    depends_on:
      - db
  # proxy:
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: ./proxy/nginx.conf
  #       target: /etc/nginx/conf.d/default.conf
  #       read_only: true
  #     - .:/app
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
